### ISSUE TITLE
Unexpected behaviour of open-choice 'other' option when using tabs

### ISSUE THREAD

**Issue by robeastwood-agency** [aehrc/smart-forms#1036]
**Describe the bug**
Within a Questionnaire organised by tabs, and with a Questionnaire item of type `open-choice`, with either repeats = true or false, the free text entry box for 'other' is populated by the value of one of the choice options after first navigating to a different tab and going back to the tab with the open choice question.

**To Reproduce**
This is evident in the Aboriginal Torres Strait Islander Health Check questionnaire found on https://www.smartforms.io/standalone 

1. open the Aboriginal Torres Strait Islander Health Check form
2. go to the tab 'Ear health and hearing'
3. under otoscopy findings for either left ear or right ear, check one or more of the choices, leaving 'other, please specify' empty and unchecked; eg:
![image](https://github.com/user-attachments/assets/abd7ebc0-8188-47c1-ae32-36fe1125e2db)

5. go to another tab, like 'mood' or 'gambling' etc
6. go back to the tab 'Ear health and hearing'
7. notice that the check box 'other' is now checked and that the entry box is prepopulated with one of the selections made in step 3; eg:
![image](https://github.com/user-attachments/assets/fd4c3765-dc96-42b0-ac79-238a3a247f2f)

**Expected behavior**
When navigating back to the open-choice question from another tab, its state regarding previously answered options, should be retained. And that the 'other' option should not be checked/prepopulated

**Comment by robeastwood-agency** [comment]
Hey Sean, I wonder if you could have another look at this one please. The behaviour described in the OP is fixed (thanks) however there is a new behaviour with the 'other' box that is unexpected.

The new bit is (also found on the CSIRO Aboriginal Torres Strait Islander Health Check questionnaire found on https://www.smartforms.io/standalone):

1. open the Aboriginal Torres Strait Islander Health Check form

1. go to the tab 'Ear health and hearing'

1. under otoscopy findings for either left ear or right ear, check 'other, please specify' and add some text
![image](https://github.com/user-attachments/assets/d32f6a29-c02f-42c0-b973-e781bc35e12b)

1. switch to another tab then go back to 'Ear health and hearing', noting that the previously entered text alongside 'other' is gone and 'other' is unchecked
![image](https://github.com/user-attachments/assets/384f47e1-ddc0-4269-a76e-376ecf306c39)

I can create a new ticket if you prefer

**Comment by fongsean** [comment]
Thanks for catching this! I'll get it resolved by the end of the week.

**Comment by fongsean** [comment]
Hi Rob, fixed it. Can you check if it's behaving as expected on your end?

**Comment by robeastwood-agency** [comment]
Perfect, thanks Sean
