### ISSUE TITLE
Getting enableWhen working from multi-select open-choice question

### ISSUE THREAD

**Issue by robeastwood-agency** [aehrc/smart-forms#1037]
Trying to figure out how to get this working...

### Requirement for form
For a user to choose one or more predefined conditions, and with each selection to have specific condition guidance text appear.

### Currently implemented with 
See simplified example here: https://gist.github.com/robeastwood-agency/1c49301cba4d0cf7da5684b265c03e06

1. Questionnaire item for list of conditions as 
  -- type = open-choice
  -- repeats=true
  -- predefined conditions in answerOption as enumerated answerString values

2. display text item condition A
 -- type = display
 -- enableWhen when above answer = "Condition A"

3. display text item condition B
 -- type = display
 -- enableWhen  when above answer = "Condition B"

4. etc for other conditions 

### Rendering expectations
1. With only condition A selected, the guidance for condition A should only appear.
2. With only condition B selected, the guidance for condition B should only appear.
3. With only condition C selected, the guidance for condition C should only appear.
4. With condition A and B selected, the guidance for condition A and B should appear. And etc for other combos A&C, B&C
5. With condition A, B and C selected, the guidance for condition A, B and C should appear.

### Rendering actual
Unfortunately we are seeing different behaviour using different platforms using the smart-forms renderer. 

#### smart-form playground https://www.smartforms.io/playground
Pasting in the above json and building form yields appearance of the guidance text only on single selection, ie expectations 1, 2 and 3 - any of the multi-selections do not have multi-texts display.

#### FHIRPath lab questionnaire tester [fhirpath-lab](https://fhirpath-lab.com/Questionnaire/tester)
This renders all of the 5 expected behaviours like this 
![image](https://github.com/user-attachments/assets/5e76d7a1-d740-4725-9397-ed3dedcf680d)

I believe that the fhirpath-lab is possibly running an older version of smart-forms.

### Question
Essentially how to make this work
- is it something to change in our definition?
- is it something for smart-forms to address?
- is it even possible? (hoping so particularly as fhirpath-lab does what we are expecting)

thank you!

**Comment by fongsean** [comment]
Hi Rob,

Thanks for reporting this! I have seen and fixed this bug way before but somehow it reemerged again - and I believe it is closely tied to issue #1036.

This is something to address on the library's end (my end). I'll get a fix out ASAP, as soon as today.

**Comment by robeastwood-agency** [comment]
Awesome thanks Sean

**Comment by fongsean** [comment]
Hi Rob,

Both issues are fixed now on my end, though not deployed yet. Just finalising some tests before they go live.

It is alright if I use the Questionnaire provided above as a Storybook example + test case?
See https://github.com/aehrc/smart-forms/pull/1038/files#diff-2b30bcb0736e38075a2236694831409a9417a8549e1bbbde23eb2d3a7f582d98R318-R409

**Comment by robeastwood-agency** [comment]
Fantastic thanks Sean; yes feel free to use this Questionnaire instance as you please

**Comment by fongsean** [comment]
Fixes deployed on v0.44.1.

Here's the storybook example: https://smartforms.csiro.au/storybook/index.html?path=/story/component-sdc-9-1-4-form-behavior-other-control--enable-when-multi-checkbox
Do a hard refresh (Ctrl + Shift + R) if you're getting an error saying the story doesn't exist.

Cheers!

**Comment by robeastwood-agency** [comment]
Great stuff! Thanks Sean, that's working as expected.
