### ISSUE TITLE
Suppress "symbol (optional)" field when using unitOption extension

### ISSUE THREAD

**Issue by samturneradha** [aehrc/smart-forms#1055]
Is your feature request related to a problem? Please describe.

When using the unitOption extension this renders a "Symbol (optional)" field as per below. The optional symbol may be required for other situations - so removing the option is not desired, but rather optionally suppressing

**Describe the solution you'd like**
Could this be optionally suppressed based on input from the form maker?

**Describe alternatives you've considered**

N/A

**Additional context**
![image](https://github.com/user-attachments/assets/646d34e9-c4a8-4911-90f1-4ef74cc6c7db)

**Comment by fongsean** [comment]
Hi Sam,

Added a `hideQuantityComparatorField` flag in the `RendererStylingStore` library API.

By default its set to `false`, which shows the optional comprator field. You can set it to `true` to suppress it.


#### Set to false (default behaviour)
https://smartforms.csiro.au/storybook/?path=/story/component-itemtype-quantity--quantity-calculation
<img width="1085" alt="image" src="https://github.com/user-attachments/assets/fc8f4f2a-d85c-46b0-9efc-bdd8db7f02f1">

#### Set to true
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/fd30c120-74d3-4c43-bfb0-b6bdc2024628">

This change will be live in **version 1.0.0-alpha.9**. Will close this issue once it's published.

**Comment by samturneradha** [comment]
Looks great :-) can't wait to test in the new version. Thanks again!
