### ISSUE TITLE
Pre-population issue on "Bit of Everything" Questionnaire sample

### ISSUE THREAD

**Issue by dattachandan** [aehrc/smart-forms#246]
Hi team

Maybe the Ontoserver down is causing some issues on sample form pre-population when I launched in EMR context

![image](https://github.com/aehrc/smart-forms/assets/2154248/2aedf454-a472-4d1d-8cb3-f4823c097b71)

![image](https://github.com/aehrc/smart-forms/assets/2154248/efa2421d-e726-490f-b86d-8cc981e68e8c)

![image](https://github.com/aehrc/smart-forms/assets/2154248/e4ca1fc1-a4c3-42ad-9519-cbc8834f2558)

![image](https://github.com/aehrc/smart-forms/assets/2154248/e44f6e5d-282b-4245-a65f-6b9690b8870c)

These vauesets maybe missing in the Bit of Everything launch

- /fhir/ValueSet/$expand?url=http://fhir.telstrahealth.com.au/tcm/ValueSet/COU
- /fhir/ValueSet/$expand?url=http://fhir.telstrahealth.com.au/tcm/ValueSet/ARE

Error

`{"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"not-found","diagnostics":"[489af43f-6aeb-494c-aff7-f7863ec63fc6]: Could not find value set http://fhir.telstrahealth.com.au/tcm/ValueSet/ARE and version null. If this is an implicit value set please make sure the url is correct. Implicit values sets for different code systems are specified in https://www.hl7.org/fhir/terminologies-systems.html."}]}`

**Comment by fongsean** [comment]
Hey Chandan!

Ontoserver can only expand a valueset it knows about. So in order for Ontoserver to support http://fhir.telstrahealth.com.au/tcm/ValueSet/COU and http://fhir.telstrahealth.com.au/tcm/ValueSet/ARE, you can POST its valuesets and codesystems to the endpoint https://r4.ontoserver.csiro.au. This endpoint is a free sandbox Ontoserver instance available for use in Australia.


It seems like both the valuesets can be expanded in https://sqlonfhir-r4.azurewebsites.net/fhir, so this is how you can do it:
We can search for the valueset by doing GET ```https://sqlonfhir-r4.azurewebsites.net/fhir/ValueSet?url=http://fhir.telstrahealth.com.au/tcm/ValueSet/COU```.
The only entry has an id of ```25b0ec04fd3511d28b3e0020182939f7```, so we can copy the entire valueset from ```https://sqlonfhir-r4.azurewebsites.net/fhir/ValueSet/25b0ec04fd3511d28b3e0020182939f7``` and POST it to ```https://r4.ontoserver.csiro.au/fhir/ValueSet```.

Next, we also need to POST its referenced codesystem. It has be done similarly by searching for ```https://sqlonfhir-r4.azurewebsites.net/fhir/CodeSystem?url=http://fhir.telstrahealth.com/tcm/CodeSystem/COU_local```.
Again, use the id ```25b0ec04fd3511d28b3e0020182939f7loc``` to search for the codesystem: ```https://sqlonfhir-r4.azurewebsites.net/fhir/CodeSystem/25b0ec04fd3511d28b3e0020182939f7loc```, and POST it to ```https://r4.ontoserver.csiro.au/fhir/ValueSet```.

I have done the steps for the http://fhir.telstrahealth.com.au/tcm/ValueSet/ARE valueset. Feel free to try the steps out for http://fhir.telstrahealth.com.au/tcm/ValueSet/COU.

**Comment by fongsean** [comment]
This one too. Can you check if the responses are helpful?
