### ISSUE TITLE
Questionnaire definition and form viewer

### ISSUE THREAD

**Issue by dattachandan** [aehrc/smart-forms#247]
Hi team

Where can I see the full definitions of individual forms in the list
![image](https://github.com/aehrc/smart-forms/assets/2154248/ce0dc7da-83d5-4f8d-8585-0fa2d1679616)

Is there any place in the src tree or is the [API server](https://api.smartforms.io/fhir/Questionnaire?_count=100 ) the only way to view them through [API calls](https://api.smartforms.io/fhir)

![image](https://github.com/aehrc/smart-forms/assets/2154248/b857b802-7d84-4bf3-8e84-4b351106f2fe)

Also, is there an authoring tool in this repo and a renderer that supports creation of the questionnaire other than handcrafting the JSON and also works for standard provided questionnaire [examples](https://build.fhir.org/ig/HL7/fhir-sirb/Questionnaire-sirb-initiate-study-questionnaire-populate.json)? i used the [LHC viewer ](https://lhncbc.github.io/questionnaire-viewer/?q=https://raw.githubusercontent.com/aehrc/smart-forms/main/packages/sdc-assemble/src/resources/subquestionnaires/Questionnaire-715AssessmentEyeHealth.json)and it could not render all fields

![image](https://github.com/aehrc/smart-forms/assets/2154248/11694ec0-da3a-4fc9-bef1-2f71b61a1de8)

**Comment by fongsean** [comment]
Hey Chandan,

The best way to get the questionnaires resources from the API server is via API calls unfortunately. The API server is an open endpoint - anyone can add their questionnaire resources to the server, so it contains the most recently updated questionnaire definitions.

The subquestionnaires in ```sdc-assemble/resources``` aren't necessarily up-to-date as they were primarily used during the initial implementation phase. You would like to look at this instead: https://github.com/aehrc/smart-forms-ig/tree/master/fsh-generated/resources. This contains the most recent subquestionnaire definitions used in the assembly process for the ```https://api.smartforms.io/fhir/Questionnaire/AboriginalTorresStraitIslanderHealthCheck``` questionnaire. We are still in the process of refining the subquestionnaires so it might not pass all validations - could be the reason why it couldn't be rendered by LHC Viewer. Really looking forward to getting it fixed up!

We also don't really have an authoring tool and questionnaire builder as far as I know, I believe @liambarnes handcrafted the JSON by himself (feel free to share your input Liam), and used the Smart Forms app as the renderer to visualize and verify the form. Though there was https://genfhi.com that was shared around recently - I personally haven't tried it out yet but it looks super promising and very well-made. It might be the solution to your needs.

**Comment by fongsean** [comment]
Same for this one, cheers!
