### ISSUE TITLE
Visual-Analog Scale (VAS)

### ISSUE THREAD

**Issue by FrankTT3D** [aehrc/smart-forms#461]
Many surveys contain a so called visual analog scale (VAS), usually ranging from 0 to 100. A patient is asked to rate e.g. her pain intensity on that scale by sliding a slider at an "analogue" position, avoiding that patients would often enter "typical numbers" like 50 or 75 or 99 .
Do you have any plans to develop such an input means?

**Comment by fongsean** [comment]
Thanks Frank, its a good suggestion. It seems like what you are describing aligns with this Questionnaire itemControl extension in the specification (Please correct me if i'm wrong!):



1 | slider | Slider | A  control where an axis is displayed between the high and low values and  the control can be visually manipulated to select a value anywhere on  the axis.
-- | -- | -- | --


http://hl7.org/fhir/r4/valueset-questionnaire-item-control.html



We haven't really encountered that need in our project use cases yet, so there are no real timeframes for developing it - but its definitely a fine addition to the conformance list . I'll update this thread when we got it implemented.

**Comment by FrankTT3D** [comment]
That is exactly the matching FHIR value-set definition for the mentioned purpose. Such a VAS question occurs roughly in 1/4th of all PROs (just guessing) and close to 100% within the combination of all questionnaires used as part of a clinical trial or post-market surveillance study. Glad to provide addl. insight if needed. Thanks for putting it on the list!

**Comment by fongsean** [comment]
Hey Frank, I have gone ahead and implemented the VAS/slider component, here's a questionnaire with sample sliders: https://api.smartforms.io/fhir/Questionnaire/TestGridSlider.

Feel free to try it out in the renderer. Happy to take any feedback, otherwise if you are good feel free to close this issue!

**Comment by FrankTT3D** [comment]
Great job! looks good and works well! Just one comment, perhaps for further improvement in case you see no easy fix:
We've had issues related to not being able to differentiate whether users really wanted to enter a value of zero (or whatever the default is) because they elected to skip the question, or that is the actual desired input. 
Our solution was to request the user to actually move the slider if they want to enter a value, which may include moving it back to the original value. Maybe there are other options that are more intuitive and allow to differentiate between no answer given/default value?

**Comment by fongsean** [comment]
Its a great question. We have thought about this before albeit for a different scenario i.e. a true/false checkbox. If a user wants to record a false value in a checkbox, a user would need to perform a check followed by an uncheck. We haven't really solved that problem yet unfortunately.

As for the VAS, I have added a non-editable value box over the top of the slider to show a "concrete" answer. Copying my comment from #537:

> Adds a non-editable display showing the value of the slider. When slider hasn't been interacted with, value is shown as "-" indicating that no answer has been provided. It provides more visibility to the user that the slider item has a concrete answer when interacted.

It still doesn't really solve the problem per se - if the answer is zero, it still requires the user to drag the slider forward and back to zero. However it does provide more transparency of whether an answer is selected or not.

Happy to talk more about it if you have any other ideas :D

**Comment by FrankTT3D** [comment]
Let's close it for the time being and solicit further feedback. I think the solution with the last addition is fine for most of the applications. Thanks a lot for the swift implementation! Great job!
