### ISSUE TITLE
Assemble & Populate Server Repo

### ISSUE THREAD

**Issue by patrick-werner** [aehrc/smart-forms#489]
Hi,

thanks for this great project. After some playing around i was wondering if you also released the code for the hapi based endpoint doing the $assemble and $populate

**Comment by fongsean** [comment]
Hi Patrick!

At the moment our HAPI server deployment only has the $assemble endpoint (in a microservice). We are using AWS Fargate to combine the HAPI server and $assemble.

Here's the directory consisting of the whole deployment:
https://github.com/aehrc/smart-forms/tree/main/deployment

Here's the code to handle the requests to either the HAPI server or $assemble:
https://github.com/aehrc/smart-forms/blob/main/deployment/csiro/lib/csiro-stack.ts

Code for their Fargate containers:
https://github.com/aehrc/smart-forms/blob/main/deployment/forms-server/lib/index.ts
https://github.com/aehrc/smart-forms/blob/main/deployment/assemble/lib/index.ts

Code for $assemble endpoint:
https://github.com/aehrc/smart-forms/tree/main/services/assemble-express

For the Smart Forms app, the $populate operation is done in-app for security reasons. There's a $populate endpoint as well but it's not really tested - you might have to put some effort in it to get it working: https://github.com/aehrc/smart-forms/tree/main/services/populate-express.

Hope that helps.

**Comment by patrick-werner** [comment]
thanks for the explanation [fongsean](https://github.com/fongsean), this helps a lot.
I will try to add assemble and extract to hapi directly / as a plugin.
