### ISSUE TITLE
Issue with Display Conditions in the Viewer

### ISSUE THREAD

**Issue by LarsDT** [aehrc/smart-forms#508]
Description:

We are working on creating medical histories for the medical context. To ensure clarity, we have defined display conditions within the questionnaire. Unfortunately, we have noticed that these display conditions are not being considered in the viewer.

Current State:
Currently, the viewer does not display any elements that are associated with display conditions. This means that essential questions and information are not visible, significantly affecting our work within the medical context.

Desired State:
The viewer should display the medical history in accordance with the defined display conditions. All elements that have display conditions should be shown or hidden as per the specified criteria. This is crucial to ensure targeted and organized medical history collection within the medical field.

We urgently need assistance to resolve this issue and ensure that the display conditions in the viewer are properly taken into account. We sincerely thank you in advance for your help and support.

**Comment by fongsean** [comment]
Hi Lars, thanks for raising this. 

If possible, can you provide me a snippet of your questionnaire to ease testing things out?

**Comment by LarsDT** [comment]
Hello, I apologize for not getting back to you sooner. We've already identified and resolved the issue. Thank you very much for your prompt response.

**Comment by fongsean** [comment]
Sorry, linked the wrong issue. 

Thanks for the heads up! Will be closing this issue in that case.
