### ISSUE TITLE
Enable github discussions?

### ISSUE THREAD

**Issue by doconnor-clintel** [aehrc/smart-forms#610]
Hi folks,
This is a pretty neat project. It would be great if there was a more general discussions area available; or a way to ask the team questions! For example currently, our main product has a very high functional overlap with the SDC concept; but doesn't speak the terminology and there's not a huge use case for interoperability yet.
Knowing other AU based EMR platforms were building on tools like this would certainly be a good nudge towards adopting the standards

**Comment by fongsean** [comment]
Hey @doconnor-clintel, sorry for the late reply!

We just recently had an internal discussion about this and decided to channel most if not all of the discussions related to SDC and the Smart Forms product to Zulip - as an effort to involve more of the FHIR community and centralise FHIR discussions at a single place.

Here's the Zulip stream we created: https://chat.fhir.org/#narrow/stream/425534-smart-forms

Feature requests can still be raised in https://github.com/aehrc/smart-forms/issues
