### ISSUE TITLE
Consider support for rendering in READ only

### ISSUE THREAD

**Issue by nielmdrec** [aehrc/smart-forms#623]
in our current project, we want to be able to fill in a QuestionnaireResponse and save it to our DB.

We also have a requirement to display a list of previously **completed** forms (QuestionnaireResponses) and allowing the user to view a past QuestionnaireResponse upon selection.  When viewing a past QuestionnaireResponse, we would want it to be rendered in READ only mode.  Is this currently supported?

**Comment by fongsean** [comment]
Added a readOnly prop at SmartFormsRenderer.
Here's a screenshot of the outcome. For tabbed forms, tabs will still work but the form cannot be filled in.
![image](https://github.com/aehrc/smart-forms/assets/52597778/84830f75-5a9c-41dc-8dc3-4c67a3ef15b0)

Let me know if I missed anything!
