### ISSUE TITLE
Renderer is crashing on certain questions

### ISSUE THREAD

**Issue by nielmdrec** [aehrc/smart-forms#733]
**Describe the bug**
I have uploaded:
   **Falls Risk Assessment**
To the SMART Forms dashboard:
    https://main.dm7mk4izbcj1q.amplifyapp.com/dashboard/questionnaires
    
**To Reproduce**
Steps to reproduce the behavior.
When I try to create a Response, if I answer Question 5 and Question 6, the application crashes:

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ol (https://main.dm7mk4izbcj1q.amplifyapp.com/assets/index-f16ce804.js:40:33862)
    at P0e (https://main.dm7mk4izbcj1q.amplifyapp.com/assets/index-f16ce804.js:38:24897)
    at https://main.dm7mk4izbcj1q.amplifyapp.com/assets/index-f16ce804.js:408:22356
    at yw (https://main.dm7mk4izbcj1q.amplifyapp.com/assets/index-f16ce804.js:40:24296)
    at Fh (https://main.dm7mk4izbcj1q.amplifyapp.com/assets/index-f16ce804.js:40:42448)
    at J0e (https://main.dm7mk4izbcj1q.amplifyapp.com/assets/index-f16ce804.js:40:41270)
    at Bf (https://main.dm7mk4izbcj1q.amplifyapp.com/assets/index-f16ce804.js:40:40309)
    at wF (https://main.dm7mk4izbcj1q.amplifyapp.com/assets/index-f16ce804.js:40:36912)
    at af (https://main.dm7mk4izbcj1q.amplifyapp.com/assets/index-f16ce804.js:38:3288)
    at Tp (https://main.dm7mk4izbcj1q.amplifyapp.com/assets/index-f16ce804.js:40:37212)

Note, the same error can be reproduced using the playground renderer:
    https://main.dm7mk4izbcj1q.amplifyapp.com/playground
    
**Expected behavior**
Previously, if we answer the all questions in  **Falls Risk Assessment**, there is no crashing and
either **low-risk-display** or **high-risk-display** item is displayed correctly

** Analysis **
The **Falls Risk Assessment** Questionnaire calculates a score for each Question group.
Then an overall score is calculated by summing up the individual scores (for each Question group)
and stored this variable:
   %riskscore
 From my troubleshooting, I could see that the %riskScore calculates correctly.
 However, it seems to crash on these items: 
      low-risk-display
      high-risk-display
      
 Specifically, it does not like the expression: 
       "%riskscore < 2"  
       
E.g.
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-enableWhenExpression",
              "valueExpression": {
                "language": "text/fhirpath",
                "expression": "%riskscore < 2"
              }
            }
          ],
          "linkId": "low-risk-display",
          "text": "Low Risk (Score < 2)",
          "type": "display"
        }
 
   Note that this was working about a week ago.

**Comment by fongsean** [comment]
Hi Niel,

Thanks for reporting this. Seems like it's caused by the enableWhenExpression changes I made in the past few days.
I have found the commit responsible for causing this, and can confirm reversing the commit fixes the issue.

I'm actively working on seeing where things went wrong. Will continue to update this thread once I push a fix, or found something valuable.

Cheers
Sean

**Comment by fongsean** [comment]
Hi Niel,

Seems to be working now. It's caused by infinite updates to the enableWhenExpression triggering an infinite loop. There was a flag designed to stop this from happening but I accidentally removed it in the last few commits while doing some refactoring.

Fixes should be live now.

**Comment by nielmdrec** [comment]
Great news! Thanks, Sean.
