### ISSUE TITLE
Checkbox unchecked on further Questionnaire completion

### ISSUE THREAD

**Issue by EWagner-tiplu** [aehrc/smart-forms#739]
My Questionnaire: [Familienanamnese.json](https://github.com/aehrc/smart-forms/files/15026581/Familienanamnese.json)

I discovered a strange bug, when I check the first checkbox ("Herz-Kreislauf-Erkrankungen"), a group of item is viewed("enableWhen"). Now, when I select any item in the newly displayed dropdown-menu, the first checkbox gets unchecked.

I double checked, if there is any conflict due to duplicate linkIds.

**Comment by fongsean** [comment]
Thanks for reporting this!

Did some debugging.

When I check the "Erkrankungen in der Familie" checkbox, This was the item `30bd342d-1eab-4913-8ad8-c2a76d84c65f`:

```
{
  "linkId": "30bd342d-1eab-4913-8ad8-c2a76d84c65f",
  "text": "Erkrankungen in der Familie",
  "answer": [
    {
      "valueCoding": {
        "id": "8ba85c6c-4e9c-441a-80c3-3303e44f9539",
        "code": "herz-kreislauf-erkrankungen",
        "system": "urn:uuid:2884b976-1bac-4822-9f3d-de18ca84e946",
        "display": "Herz-Kreislauf-Erkrankungen"
      }
    }
  ]
}
```

Here's the item after selecting a value:

```
{
  "linkId": "30bd342d-1eab-4913-8ad8-c2a76d84c65f",
  "text": "Erkrankungen in der Familie",
  "item": [
    {
      "linkId": "a2aa134f-64b5-4f48-fc32-91b50a786c1b",
      "text": "Herz-Kreislauf-Erkrankungen",
      "item": [
        {
          "linkId": "10fcd38b-27ab-404d-a4cb-d773d8312b30",
          "text": "Herz-Kreislauf-Erkrankungen",
          "answer": [
            {
              "valueCoding": {
                "id": "b974b598-15ef-41cf-f22f-b18fcbe643be",
                "code": "-herzinsuffizienz",
                "system": "urn:uuid:80dfb587-1b0f-4ed7-e53c-064ec33ca7a4",
                "display": " Herzinsuffizienz"
              }
            }
          ]
        }
      ]
    }
  ]
}
```

It suggests that answer was replaced by the nested item. I think it can be easily fixed by preserving item.answer, and only updating item.item.

**Comment by fongsean** [comment]
Resolved. Great catch, thank you!
