### ISSUE TITLE
item of type dateTime clears the date component when the user enters the time component

### ISSUE THREAD

**Issue by nielmdrec** [aehrc/smart-forms#822]
**Describe the bug**
A dateTime field is rendered as 3 components:
1. date component (with date picker)
2. time component
3. AM/PM component
The validation of these 3 components for the one dateTime field is causing issue depending on the order that the
data is entered

**To Reproduce**
For a dateTime item, e.g.
      "item":[
        {
          "linkId":"awsLastAlcoholUse",
          "text":"Last Alcohol Use (DD/MM/YYYY HH:MM)",
          "required":false,
          "type":"dateTime"
        },
Do the following steps:
1. First select a date using the date picker in the date component -> selected date is displayed in the date component
2. Proceed to enter a time in the time component, for example: 12:40
   Result: 
   * date component value is replaced with 'Invalid Date' 
      and red error message below the field: 'Input is an invalid date'
   * time component has red message below: 'Specify the period as AM or PM'
      This can be cleared by choosing AM or PM in the AM/PM component.
      However, the user is forced to fill in the date component again.

**Expected behavior**
The user should be able to enter all 3 components:
1. date component (with date picker)
2. time component
3. AM/PM component
Before the entire dateTime field is validated.

**Comment by fongsean** [comment]
Thanks for catching this. Resolved in version 0.32.1.

**Comment by nielmdrec** [comment]
Thanks so much for the fix.  I confirm that it is working now.
