### ISSUE TITLE
Path Not Found error when running the app using smart-form-renderer version >= 0.31.2

### ISSUE THREAD

**Issue by basilmdrecords** [aehrc/smart-forms#839]
**Describe the bug**
I update smart-form renderer to latest version (0.33.1) in my app, when I run my app I got path not found error:
![Screenshot 2024-06-04 142959](https://github.com/aehrc/smart-forms/assets/110363768/ad9eb996-3c99-409b-af07-b7e856a334be)

location where path is not found:
![Screenshot 2024-06-05 093707](https://github.com/aehrc/smart-forms/assets/110363768/79be3041-730a-492c-b6f4-d871a10c38e8)

look at the node_modules, smart-form-renderer build using pascal case (StorybookWrappers) instead of camel case (storybookWrappers):
![Screenshot 2024-06-05 091843](https://github.com/aehrc/smart-forms/assets/110363768/c3d9966e-4dcc-4cfe-b458-b3baabafe46f)

**To Reproduce**
node version: 18.17.1
yarn version: 1.22.19
app build using CRA

install @aehrc/smart-forms-renderer to the app
```
yarn add @aehrc/smart-forms-renderer
```

import SmartFormsRenderer from @aehrc/smart-forms-renderer
```
import { SmartFormsRenderer } from '@aehrc/smart-forms-renderer';
```

use SmartFormsRenderer component in the app
```
return (
  <SmartFormsRenderer
    questionnaire={questionnaire}
  />
)
```

run the app
```
yarn start
```

**Expected behavior**
After I updated smart-form-renderer my app still running properly with no error come from smart-form-renderer module

**Comment by fongsean** [comment]
Hi @basilmdrecords, thanks for raising this.

I've cleaned up the /lib folder and re-published. Can you try out the latest version v0.34.2?

I indeed changed `StorybookWrappers` to `storybookWrappers` a couple minor versions ago. I think the issue was that the ts compilation didn't clean up the old `StorybookWrappers` folder and assumed it was the same folder to write to.

Let me know how it goes.

**Comment by basilmdrecords** [comment]
thank you.. it's fixed

**Comment by fongsean** [comment]
@ir4y I believe this is the issue you are facing. I have cleaned it up for versions >0.34.x.

Try out the latest versions - 0.35.6 or 0.35.5.
