### ISSUE TITLE
Initial.valueBoolean crashing form

### ISSUE THREAD

**Issue by liambarnes** [aehrc/smart-forms#866]
**Describe the bug**
Questionnaire with an Intial.valueBoolean set seems to be preventing the form from loading and crashing the form.
See https://smartforms.csiro.au/api/fhir/Questionnaire/QITesting/_history/5 (e.g. line 175 and 190)

**To Reproduce**
From https://ehr.smartforms.io/ launch Questionnaire QITesting (https://smartforms.csiro.au/ig/Questionnaire/QITesting)

**Expected behavior**
Form is launched with boolean values "false" prepopulated.

**Comment by fongsean** [comment]
Fixed. Try it out with https://ehr.smartforms.io/ launch Questionnaire QITestingv5 (https://smartforms.csiro.au/ig/Questionnaire/QITestingv5).

**Comment by liambarnes** [comment]
Thanks. Looking good.
