### ISSUE TITLE
Support the display of page group

### ISSUE THREAD

**Issue by ryuuzake** [aehrc/smart-forms#940]
**Is your feature request related to a problem? Please describe.**
Unable to render Page group properly

**Describe the solution you'd like**
I want to be able to display a page group using SMART Forms

**Describe alternatives you've considered**
I can contribute to create this feature

**Additional context**
[page-example.json](https://github.com/user-attachments/files/16414130/page-example.json)
| Page 1 | Page 2 |
| ------- | -------- |
| ![image](https://github.com/user-attachments/assets/3ecaf7e0-c7f5-4e94-a331-89323626c7c7) | ![image](https://github.com/user-attachments/assets/cae76b27-5110-445f-b2f5-9f232b59bf92) |

**Comment by fongsean** [comment]
Hi @ryuuzake,

Thanks for contributing! Happy to work through a pull request to get feature into the renderer.

A few points to make:
1.  I think this would be a really good opportunity to use https://mui.com/material-ui/react-pagination/, which will greatly enhance UX.
   - We know how many pages there are in a Questionnaire, therefore we should be able to use a pagination section to inform how many pages the user has to work through.
   - User can "skip" pages if they want, i.e clicking on "page 3" while currently on the first page

2. I'm just thinking about the enableWhen/calculationExpression aspect of this. It might be similar to a "tab", where a tab disappears and appears based on form inputs. Maybe disable the pagination button if the page is "off"?

3. The spec also highlights this (in https://hl7.org/fhir/extensions/CodeSystem-questionnaire-item-control.html):

    > This designation may also influence pagination when printing questionnaires.
 - This means that pagination should also appear in the app's "Preview mode".
 
 
 <br/>
 
 Overall, this is a really good addition to the form renderer 👍 
 Can you create a pull request? Happy to collaborate through some of the points mentioned above.

**Comment by lamurian** [comment]
Hi @fongsean, I'd love to also chime in to this discussion.

>     1. I think this would be a really good opportunity to use https://mui.com/material-ui/react-pagination/, which will greatly enhance UX.
> 
> 
>     * We know how many pages there are in a Questionnaire, therefore we should be able to use a pagination section to inform how many pages the user has to work through.
> 
>     * User can "skip" pages if they want, i.e clicking on "page 3" while currently on the first page

You raised an important point here, and I completely agree that showing the current page and total number of pages would improve the UX. However, I'm afraid that the implementation provided by material UI reference won't render well in a mobile display. As an alternative, I'm thinking about the following mockup:

![image](https://github.com/user-attachments/assets/cfd1baf5-7625-4413-a572-217ad71cc1e5)

In this mockup, the user can see the page indicator and the total number of pages. When the user clicks the page indicator, the user can select a different page to visit. The prev/next page button is more accessible, and I make the next page button slightly larger. The intention behind this design is to make it easier for the user to proceed when completing the questionnaire.

I'd love to hear your thoughts on this matter.

**Comment by ryuuzake** [comment]
First of all, thank you for commenting on the issue

I'll try to address all the points you make:
1. After tinkering with the source code, I already get it working by copying the `Tab` logic. I guess your suggestions would make sense. By using pagination, users to able to transverse the Questionnaire more freely
2. That's a great idea. I haven't test that scenario when tinkering with the source code. Actually, I'm kinda new with the FHIR Item Control Spec and SDC. I'll happy if you could give guide or give json examples for that scenario 
3. Actually I didn't think much about this.. Where can I learn more about this "Preview Mode" in the repo?

Since I'm new, I'd like to confirm some stuff. Mostly about the `page` spec itself. I have 3 json files containing Questionnaire with a `page` item. I hope you can help me determine if those examples is within `page` spec or not.

[page-example.json](https://github.com/user-attachments/files/16437806/page-example.json)
[page.json](https://github.com/user-attachments/files/16437815/page.json)
[page-of-everything.json](https://github.com/user-attachments/files/16437816/page-of-everything.json)

Actually this feature request also came with requirements. Some of the requirements are like this:
1. Page Prev & Next Button is customizeable
2. Option to show or hide the pagination

I'd like to here you inputs on this. From my side, I thought it would be better if we can expose some kind of `zustand` store to the end user so that they could change those components more freely

**Comment by fongsean** [comment]
Considering mobile usage is a really good point.

I went though Riza's pull request #947 and those changes look really good. See that thread for PR details.

Those three example Questionnaires are on point. They look great to me.

> 
    This feature request also came with requirements. Some of the requirements are like this:

    1. Page Prev & Next Button is customizable
    2. Option to show or hide the pagination

Customising the renderer is usually done via MUI theming - though I understand that the options are quite limited (colors, box shadows, paddings, etc - but not button sizes). What kind of customisation features do you need to support?

As for the second point, I think we can sidestep the problem completely by not having a pagination.

**Comment by fongsean** [comment]
> 

    The spec also highlights this (in https://hl7.org/fhir/extensions/CodeSystem-questionnaire-item-control.html):

    This designation may also influence pagination when printing questionnaires.

    This means that pagination should also appear in the app's "Preview mode".
    
    
If you go to this link https://smartforms.csiro.au/launch?iss=https%3A%2F%2Fproxy.smartforms.io%2Fv%2Fr4%2Ffhir&launch=WzAsInBhdC1zZiIsInByaW1hcnktcGV0ZXIiLCIiLDAsMCwwLCJmaGlyVXNlciBvbmxpbmVfYWNjZXNzIG9wZW5pZCBwcm9maWxlIHBhdGllbnQvQ29uZGl0aW9uLnJzIHBhdGllbnQvT2JzZXJ2YXRpb24ucnMgbGF1bmNoIHBhdGllbnQvRW5jb3VudGVyLnJzIHBhdGllbnQvUXVlc3Rpb25uYWlyZVJlc3BvbnNlLmNydWRzIHBhdGllbnQvUGF0aWVudC5ycyIsImh0dHBzOi8vc21hcnRmb3Jtcy5jc2lyby5hdSIsImE1N2Q5MGUzLTVmNjktNGI5Mi1hYTJlLTI5OTIxODA4NjNjMSIsIiIsIiIsIiIsIiIsMCwxLCJ7XCJyb2xlXCI6XCJxdWVzdGlvbm5haXJlLXJlbmRlci1vbi1sYXVuY2hcIixcImNhbm9uaWNhbFwiOlwiaHR0cDovL3d3dy5oZWFsdGguZ292LmF1L2Fzc2Vzc21lbnRzL21icy83MTV8MC4xLjAtYXNzZW1ibGVkXCIsXCJ0eXBlXCI6XCJRdWVzdGlvbm5haXJlXCJ9IiwiaHR0cHM6Ly9wcm94eS5zbWFydGZvcm1zLmlvL3YvcjQvZmhpciIsZmFsc2Vd, there is a "Preview" button on the left sidebar. That shows a preview of the current form. 

This Preview isn't a part of the Questionnaire renderer, it's part of the Smart Forms app. 
https://github.com/aehrc/smart-forms/blob/main/apps/smart-forms-app/src/features/renderer/components/FormPreviewPage/FormPreview.tsx

I think having pagination in the preview isn't a good idea after all - given how the "page" extension can be used in a way that the form has "partial" and "full" pages. First thought, It might make sense to have paged previews for "full" pages but not for "partial" pages. But that would make it inconsistent and confuse users.

I think we can hold off from implementing this until there's a real use case for paged previews.

Overall, well done - changes look great!
