### ISSUE TITLE
gtable not working ?

### ISSUE THREAD

**Issue by davidhay25** [aehrc/smart-forms#963]
**Describe the bug**
If I understand the extension correctly, the Q segment below should render the 2 child elements as a single row (ie on the same line)...

{
                    "extension": [
                        {
                            "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
                            "valueCodeableConcept": {
                                "coding": [
                                    {
                                        "system": "http://hl7.org/fhir/questionnaire-item-control",
                                        "code": "gtable"
                                    }
                                ]
                            }
                        }
                    ],
                    "linkId": "Patient.DeathInformation",
                    "definition": "Group",
                    "text": "Death information",
                    "type": "group",
                    "item": [
                        {
                            "linkId": "Patient.DeathInformation.DateDeath",
                            "definition": "date",
                            "text": "Date of death",
                            "type": "date"
                        },
                        {
                            "linkId": "Patient.DeathInformation.DateDeathInfoSource",
                            "definition": "CodeableConcept",
                            "text": "Date of death information source",
                            "type": "choice",
                            "answerOption": [
                                {
                                    "valueCoding": {
                                        "display": "There is neither a ValueSet nor options"
                                    }
                                }
                            ]
                        }
                    ]
                }

**Comment by davidhay25** [comment]
BTW just to confirm that I tried it in the online playground and they rendered on separate lines

**Comment by fongsean** [comment]
Hi @davidhay25,

Seems like all you need to do is to add `"repeats": true,` to the item!


```
{
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
          "valueCodeableConcept": {
            "coding": [
              {
                "system": "http://hl7.org/fhir/questionnaire-item-control",
                "code": "gtable"
              }
            ]
          }
        }
      ],
      "linkId": "Patient.DeathInformation",
      "definition": "Group",
      "text": "Death information",
      "type": "group",
      "repeats": true,
      "item": [
        {
          "linkId": "Patient.DeathInformation.DateDeath",
          "definition": "date",
          "text": "Date of death",
          "type": "date"
        },
        {
          "linkId": "Patient.DeathInformation.DateDeathInfoSource",
          "definition": "CodeableConcept",
          "text": "Date of death information source",
          "type": "choice",
          "answerOption": [
            {
              "valueCoding": {
                "display": "There is neither a ValueSet nor options"
              }
            }
          ]
        }
      ]
    }
```

Based on the definition of `gtable` in https://hl7.org/fhir/extensions/CodeSystem-questionnaire-item-control.html I've initially interpreted it as a table where it works as a repeating group. Now, I think it also makes sense where if the table isn't a repeating group, it would render nicely too - just without the "Add row" button.

**Comment by davidhay25** [comment]
Thanks Sean! I was thinking of using it as a sneaky way to have elements across the screen rather than vertically...
